"use client";
import {useEffect,useState} from "react";
import {Bell,Bookmark,Heart,Home,MessageCircle,Plus,Search,Settings,Share2,User} from "lucide-react";
import {createClient} from "@/lib/supabase/client";

type Post={id:string;body:string;category:string;status:string;created_at:string;author_id:string;profiles:{display_name:string|null;username:string|null;avatar_url:string|null}|null;likes:number;responses:number};
export default function HomePage(){
 const [tab,setTab]=useState("Discover"); const [user,setUser]=useState<any>(null); const [posts,setPosts]=useState<Post[]>([]); const [loading,setLoading]=useState(true); const supabase=createClient();
 async function loadPosts(){setLoading(true); const {data,error}=await supabase.from("posts").select("id,body,category,status,created_at,author_id,profiles(display_name,username,avatar_url)").eq("content_type","text").order("created_at",{ascending:false}).limit(50); if(!error&&data){const ids=data.map((p:any)=>p.id); const [likes,responses]=await Promise.all([supabase.from("likes").select("post_id").in("post_id",ids),supabase.from("responses").select("post_id").in("post_id",ids)]); const lc=Object.fromEntries(ids.map(id=>[id,0])); const rc=Object.fromEntries(ids.map(id=>[id,0])); (likes.data??[]).forEach((x:any)=>lc[x.post_id]++); (responses.data??[]).forEach((x:any)=>rc[x.post_id]++); setPosts((data as any[]).map(p=>({...p,likes:lc[p.id],responses:rc[p.id]})))} setLoading(false)}
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user)); loadPosts(); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null)); return()=>data.subscription.unsubscribe()},[]);
 return <main className="app-shell"><header className="topbar"><div className="brand"><div className="brand-icon">G</div><span>Gista</span></div><button className="icon-btn" aria-label="Settings"><Settings size={20}/></button></header>
 <section className="content"><div className="feed-tabs">{["Discover","Following","Trending"].map(x=><button key={x} className={tab===x?"tab active":"tab"} onClick={()=>setTab(x)}>{x}</button>)}</div>
 <div className="composer"><div className="avatar">{user?.email?.[0]?.toUpperCase()??"G"}</div><button className="composer-input" onClick={()=>location.href="/create"}>What’s on your mind?</button><button className="create-btn" onClick={()=>location.href="/create"}><Plus size={19}/></button></div>
 <div className="feed">{loading?<p>Loading Gists…</p>:posts.length===0?<div className="empty-state"><h3>No Gists yet</h3><p>Be the first person to start a Gist.</p></div>:posts.map(p=><article className="post" key={p.id}><div className="post-head"><div className="avatar">{p.profiles?.display_name?.[0]?.toUpperCase()??"G"}</div><div className="identity"><strong>{p.profiles?.display_name??"Gista User"}</strong><span>@{p.profiles?.username??"user"} · {new Date(p.created_at).toLocaleString()}</span></div><span className="category">{p.category}</span></div><p className="post-text">{p.body}</p><div className="gist-status"><span className={p.status==="trending"?"hot":"dot"}>{p.status==="trending"?"🔥":"●"}</span>{p.status.charAt(0).toUpperCase()+p.status.slice(1)}<button>Gist DNA</button></div><div className="actions"><button><Heart size={18}/> {p.likes}</button><button><MessageCircle size={18}/> {p.responses}</button><button><Share2 size={18}/></button><button><Bookmark size={18}/></button></div></article>)}</div>
 </section><nav className="bottom-nav"><button className="nav-active"><Home/><span>Home</span></button><button><Search/><span>Search</span></button><button className="nav-create" onClick={()=>location.href="/create"}><Plus/></button><button><Bell/><span>Notifications</span></button><button onClick={()=>location.href="/profile"}><User/><span>Profile</span></button></nav></main>}