"use client";
import {useEffect,useState} from "react";
import {Bell,Bookmark,Heart,Home,MessageCircle,Plus,Search,Settings,Share2,User} from "lucide-react";
import {createClient} from "@/lib/supabase/client";

type Post={id:string;body:string|null;content_type:string;media_url:string|null;category:string;status:string;created_at:string;author_id:string;profiles:{display_name:string|null;username:string|null;avatar_url:string|null}|null;likes:number;responses:number;liked:boolean;saved:boolean};
export default function HomePage(){
 const [tab,setTab]=useState("Discover"); const [user,setUser]=useState<any>(null); const [posts,setPosts]=useState<Post[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const supabase=createClient();
 async function loadPosts(){setLoading(true); let query=supabase.from("posts").select("id,body,content_type,media_url,category,status,created_at,author_id,profiles(display_name,username,avatar_url)"); if(tab==="Trending") query=query.eq("status","trending"); if(tab==="Following"&&user){const {data:f}=await supabase.from("follows").select("following_id").eq("follower_id",user.id); query=query.in("author_id",(f??[]).map((x:any)=>x.following_id));} const {data,error}=await query.order("created_at",{ascending:false}).limit(50); if(!error&&data){const ids=data.map((p:any)=>p.id); const [likes,responses,saves]=await Promise.all([supabase.from("likes").select("post_id,user_id").in("post_id",ids),supabase.from("responses").select("post_id").in("post_id",ids),supabase.from("saves").select("post_id,user_id").in("post_id",ids)]); const lc=Object.fromEntries(ids.map(id=>[id,0])); const rc=Object.fromEntries(ids.map(id=>[id,0])); (likes.data??[]).forEach((x:any)=>lc[x.post_id]++); (responses.data??[]).forEach((x:any)=>rc[x.post_id]++); const liked=new Set((likes.data??[]).filter((x:any)=>x.user_id===user?.id).map((x:any)=>x.post_id)); const saved=new Set((saves.data??[]).filter((x:any)=>x.user_id===user?.id).map((x:any)=>x.post_id)); setPosts((data as any[]).map(p=>({...p,likes:lc[p.id],responses:rc[p.id],liked:liked.has(p.id),saved:saved.has(p.id)})))} setLoading(false)}
 async function toggleLike(p:Post){if(!user){location.href="/auth";return} setBusy(p.id+"l"); if(p.liked){await supabase.from("likes").delete().eq("post_id",p.id).eq("user_id",user.id)}else{await supabase.from("likes").insert({post_id:p.id,user_id:user.id})} setPosts(x=>x.map(q=>q.id===p.id?{...q,liked:!q.liked,likes:q.likes+(q.liked?-1:1)}:q)); setBusy(null)} async function toggleSave(p:Post){if(!user){location.href="/auth";return} setBusy(p.id+"s"); if(p.saved){await supabase.from("saves").delete().eq("post_id",p.id).eq("user_id",user.id)}else{await supabase.from("saves").insert({post_id:p.id,user_id:user.id})} setPosts(x=>x.map(q=>q.id===p.id?{...q,saved:!q.saved}:q)); setBusy(null)} useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);}).then(loadPosts); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null)); return()=>data.subscription.unsubscribe()},[tab,user?.id]);
 return <main className="app-shell"><header className="topbar"><div className="brand"><div className="brand-icon">G</div><span>Gista</span></div><button className="icon-btn" aria-label="Settings"><Settings size={20}/></button></header>
 <section className="content"><div className="feed-tabs">{["Discover","Following","Trending"].map(x=><button key={x} className={tab===x?"tab active":"tab"} onClick={()=>setTab(x)}>{x}</button>)}</div>
 <div className="composer"><div className="avatar">{user?.email?.[0]?.toUpperCase()??"G"}</div><button className="composer-input" onClick={()=>location.href="/create"}>What’s on your mind?</button><button className="create-btn" onClick={()=>location.href="/create"}><Plus size={19}/></button></div>
 <div className="feed">{loading?<p>Loading Gists…</p>:posts.length===0?<div className="empty-state"><h3>No Gists yet</h3><p>Be the first person to start a Gist.</p></div>:posts.map(p=><article className="post" key={p.id}><div className="post-head"><div className="avatar">{p.profiles?.display_name?.[0]?.toUpperCase()??"G"}</div><div className="identity"><strong>{p.profiles?.display_name??"Gista User"}</strong><span>@{p.profiles?.username??"user"} · {new Date(p.created_at).toLocaleString()}</span></div><span className="category">{p.category}</span></div><>{p.content_type==="photo"&&p.media_url&&<img src={p.media_url} alt="Gist photo" style={{width:"100%",borderRadius:16,marginTop:10}}/>}{p.content_type==="voice"&&p.media_url&&<audio controls src={p.media_url} style={{width:"100%",marginTop:10}}/ >}{p.body&&<p className="post-text">{p.body}</p>}</><div className="gist-status"><span className={p.status==="trending"?"hot":"dot"}>{p.status==="trending"?"🔥":"●"}</span>{p.status.charAt(0).toUpperCase()+p.status.slice(1)}<button>Gist DNA</button></div><div className="actions"><button onClick={()=>toggleLike(p)} disabled={busy===p.id+"l"}><Heart size={18} fill={p.liked?"currentColor":"none"}/> {p.likes}</button><button onClick={()=>location.href="/gist/"+p.id}><MessageCircle size={18}/> {p.responses}</button><button onClick={()=>navigator.share?navigator.share({title:"Gista",text:p.body,url:location.origin+"/gist/"+p.id}):navigator.clipboard.writeText(location.origin+"/gist/"+p.id)}><Share2 size={18}/></button><button onClick={()=>toggleSave(p)} disabled={busy===p.id+"s"}><Bookmark size={18} fill={p.saved?"currentColor":"none"}/></button></div></article>)}</div>
 </section><nav className="bottom-nav"><button className="nav-active"><Home/><span>Home</span></button><button><Search/><span>Search</span></button><button className="nav-create" onClick={()=>location.href="/create"}><Plus/></button><button onClick={()=>location.href="/notifications"}><Bell/><span>Notifications</span></button><button onClick={()=>location.href="/profile"}><User/><span>Profile</span></button></nav></main>}