"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
import {signOut} from "@/lib/auth";
export default function SettingsPage(){const supabase=createClient();const [email,setEmail]=useState("");const [privateAccount,setPrivateAccount]=useState(false);const [followingPrivate,setFollowingPrivate]=useState(false);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [totalLikes,setTotalLikes]=useState(0);const [totalResponses,setTotalResponses]=useState(0);
useEffect(()=>{supabase.auth.getUser().then(async({data})=>{setEmail(data.user?.email??"");if(data.user){const [{data:p},{data:posts}]=await Promise.all([supabase.from("profiles").select("is_private,following_private").eq("id",data.user.id).maybeSingle(),supabase.from("posts").select("id").eq("author_id",data.user.id)]);setPrivateAccount(Boolean(p?.is_private));setFollowingPrivate(Boolean(p?.following_private));const postIds=(posts??[]).map((post:{id:string})=>post.id);if(postIds.length){const [{count:likes,error:likesError},{count:responses,error:responsesError}]=await Promise.all([supabase.from("likes").select("post_id",{count:"exact",head:true}).in("post_id",postIds),supabase.from("responses").select("id",{count:"exact",head:true}).in("post_id",postIds)]);if(likesError||responsesError){setMessage(likesError?.message??responsesError?.message??"Could not load activity.")}setTotalLikes(likes??0);setTotalResponses(responses??0)}}setLoading(false)})},[supabase]);
async function privacy(v:boolean){setPrivateAccount(v);const {data:{user}}=await supabase.auth.getUser();if(user){const {error}=await supabase.from("profiles").update({is_private:v}).eq("id",user.id);setMessage(error?error.message:"Privacy updated.")}}
async function followingPrivacy(v:boolean){setFollowingPrivate(v);const {data:{user}}=await supabase.auth.getUser();if(user){const {error}=await supabase.from("profiles").update({following_private:v}).eq("id",user.id);setMessage(error?error.message:"Following privacy updated.")}}
async function deleteAccount(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;if(!confirm("Delete your Gista account permanently? This cannot be undone?"))return;setMessage("Deleting account…");const {data:{session}}=await supabase.auth.getSession();const base=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!base||!session){setMessage("Unable to start account deletion.");return}const res=await fetch(base+"/functions/v1/delete-account",{method:"POST",headers:{Authorization:"Bearer "+session.access_token}});if(!res.ok){const body=await res.text();setMessage(body||"Account deletion failed.");return}await supabase.auth.signOut();location.href="/auth"}
return <main className="content"><header className="simple-header settings-header" style={{borderBottom:"0"}}><Link href="/profile">‹ Profile</Link><strong>Settings</strong></header>{loading?<p>Loading…</p>:<div className="feed"><section className="create-card"><h2>Account</h2><p>{email}</p><Link className="primary small" href="/profile">Edit profile</Link></section><section className="create-card"><h2>Your Gista activity</h2><div className="profile-metrics"><div className="profile-metric"><strong>{totalLikes}</strong><span>Total likes received</span></div><div className="profile-metric"><strong>{totalResponses}</strong><span>Total responses received</span></div></div></section><section className="create-card"><h2>Notifications</h2><Link href="/notifications">Open notifications</Link></section><section className="create-card"><h2>Privacy</h2><label><input type="checkbox" checked={privateAccount} onChange={e=>privacy(e.target.checked)}/> Private account</label><p>When enabled, your profile and Gists are visible only to you and people who follow you.</p><label><input type="checkbox" checked={followingPrivate} onChange={e=>followingPrivacy(e.target.checked)}/> Private following</label><p>When enabled, only you can see the people you follow. Your following count remains visible.</p></section><section className="create-card"><h2>Safety</h2><Link href="/settings/blocked">Blocked users</Link></section><section className="create-card"><h2>Security</h2><Link href="/auth/forgot-password">Change/reset password</Link></section><section className="create-card"><h2>Help & Support</h2><div style={{display:"grid",gap:10}}><Link href="/help">Help Center</Link><Link href="/how-to-use">How to use Gista</Link></div></section><section className="create-card"><h2>About & Privacy</h2><div style={{display:"grid",gap:10}}><Link href="/about">About Gista</Link><Link href="/privacy">Privacy information</Link></div></section><section className="create-card"><button className="primary small" onClick={signOut}>Log out</button><button className="danger small" onClick={deleteAccount}>Delete account</button></section>{message&&<div className="auth-message">{message}</div>}</div>}</main>}
