"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
import {signOut} from "@/lib/auth";
export default function SettingsPage(){const supabase=createClient();const [email,setEmail]=useState("");const [privateAccount,setPrivateAccount]=useState(false);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
useEffect(()=>{supabase.auth.getUser().then(async({data})=>{setEmail(data.user?.email??"");if(data.user){const {data:p}=await supabase.from("profiles").select("is_private").eq("id",data.user.id).maybeSingle();setPrivateAccount(Boolean(p?.is_private));}setLoading(false)})},[]);
async function privacy(v:boolean){setPrivateAccount(v);const {data:{user}}=await supabase.auth.getUser();if(user){const {error}=await supabase.from("profiles").update({is_private:v}).eq("id",user.id);setMessage(error?error.message:"Privacy updated.");}}
async function deleteAccount(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;if(!confirm("Delete your Gista account permanently? This cannot be undone."))return;setMessage("Deleting account…");const {data:{session}}=await supabase.auth.getSession();const base=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!base||!session){setMessage("Unable to start account deletion.");return}const res=await fetch(base+"/functions/v1/delete-account",{method:"POST",headers:{Authorization:"Bearer "+session.access_token}});if(!res.ok){const body=await res.text();setMessage(body||"Account deletion failed.");return}await supabase.auth.signOut();location.href="/auth";}
return <main className="content"><header className="simple-header"><Link href="/profile">‹ Profile</Link><strong>Settings</strong></header>{loading?<p>Loading…</p>:<div className="feed"><section className="create-card"><h2>Account</h2><p>{email}</p><Link className="primary small" href="/profile">Edit profile</Link></section><section className="create-card"><h2>Notifications</h2><Link href="/notifications">Open notifications</Link></section><section className="create-card"><h2>Privacy</h2><label><input type="checkbox" checked={privateAccount} onChange={e=>privacy(e.target.checked)}/> Private account</label><p>When enabled, your profile and Gists are visible only to you and people who follow you.</p></section><section className="create-card"><h2>Safety</h2><Link href="/settings/blocked">Blocked users</Link></section><section className="create-card"><h2>Security</h2><Link href="/auth/forgot-password">Change/reset password</Link></section><section className="create-card"><h2>About Gista</h2><p>Gista — a place where people come to talk.</p></section><section className="create-card"><button className="primary small" onClick={signOut}>Log out</button><button className="danger small" onClick={deleteAccount}>Delete account</button></section>{message&&<div className="auth-message">{message}</div>}</div>}</main>}