"use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
type Reply={id:string;body:string;created_at:string;author_id:string;profiles:{display_name:string|null;username:string|null}|null}; type Response={id:string;body:string;created_at:string;author_id:string;profiles:{display_name:string|null;username:string|null}|null;replies:Reply[]};
export default function GistPage(){
 const {id}=useParams<{id:string}>();const router=useRouter();const supabase=createClient();const [post,setPost]=useState<any>(null);const [responses,setResponses]=useState<Response[]>([]);const [text,setText]=useState("");const [replyText,setReplyText]=useState<Record<string,string>>({});const [openReply,setOpenReply]=useState<string|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 async function load(){const [{data:p,error:pe},{data:r,error:re}]=await Promise.all([supabase.from("posts").select("id,body,category,created_at,profiles(display_name,username)").eq("id",id).single(),supabase.from("responses").select("id,body,created_at,author_id,profiles(display_name,username),replies(id,body,created_at,author_id,profiles(display_name,username))").eq("post_id",id).order("created_at",{ascending:true})]);if(pe)setError(pe.message);setPost(p);setResponses(((r??[]) as any[]).map(x=>({...x,replies:x.replies??[]})) as Response[]);setLoading(false)}
 useEffect(()=>{load()},[id]);
 async function respond(){setError("");const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/auth");return}if(!text.trim())return;const {error:e}=await supabase.from("responses").insert({post_id:id,author_id:user.id,content_type:"text",body:text.trim()});if(e)setError(e.message);else{setText("");await load()}}
 if(loading)return <main className="content"><p>Loading Gist…</p></main>;
 if(!post)return <main className="content"><p>Gist not found.</p></main>;
 return <main className="content"><button onClick={()=>router.back()}>← Back</button><article className="post"><div className="post-head"><div className="avatar">{post.profiles?.display_name?.[0]?.toUpperCase()??"G"}</div><div className="identity"><strong>{post.profiles?.display_name??"Gista User"}</strong><span>@{post.profiles?.username??"user"} · {new Date(post.created_at).toLocaleString()}</span></div><span className="category">{post.category}</span></div><p className="post-text">{post.body}</p></article>
 <section className="create-card"><h3>Join the Gist</h3><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write a response…"/><button className="primary" onClick={respond}>Post response</button>{error&&<div className="auth-message">{error}</div>}</section>
 <section className="feed"><h3>{responses.length} {responses.length===1?"Response":"Responses"}</h3>{responses.length===0?<p>No responses yet. Start the Gist.</p>:responses.map(r=><article className="post" key={r.id}><div className="post-head"><div className="avatar">{r.profiles?.display_name?.[0]?.toUpperCase()??"G"}</div><div className="identity"><strong>{r.profiles?.display_name??"Gista User"}</strong><span>@{r.profiles?.username??"user"} · {new Date(r.created_at).toLocaleString()}</span></div></div><p className="post-text">{r.body}</p><button className="response-reply" onClick={()=>setOpenReply(openReply===r.id?null:r.id)}>Reply</button>{openReply===r.id&&<div className="reply-box"><textarea value={replyText[r.id]??""} onChange={e=>setReplyText({...replyText,[r.id]:e.target.value})} placeholder="Write a reply…"/><button className="primary small" onClick={async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/auth");return}const body=(replyText[r.id]??"").trim();if(!body)return;const {error:e}=await supabase.from("replies").insert({response_id:r.id,author_id:user.id,content_type:"text",body});if(e)setError(e.message);else{setReplyText({...replyText,[r.id]:""});setOpenReply(null);await load()}}}>Post reply</button></div>}{r.replies?.length>0&&<div className="replies">{r.replies.map(q=><div className="reply" key={q.id}><strong>{q.profiles?.display_name??"Gista User"}</strong><span> @{q.profiles?.username??"user"}</span><p>{q.body}</p></div>)}</div></article>)}</section></main>