"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Bookmark, Heart, ImagePlus, Mic, MoreHorizontal, Share2, Square } from "lucide-react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import VoiceNote from "@/components/VoiceNote";

type Profile = { id: string; display_name: string | null; username: string | null; avatar_url: string | null };
type Reply = { id: string; body: string | null; content_type: string; media_url: string | null; voice_duration_seconds: number | null; created_at: string; author_id: string; profiles: Profile | null; likes: number; liked: boolean };
type Comment = { id: string; body: string | null; content_type: string; media_url: string | null; voice_duration_seconds: number | null; created_at: string; author_id: string; profiles: Profile | null; replies: Reply[]; likes: number; liked: boolean };
type Post = { id: string; author_id: string; body: string | null; content_type: string; media_url: string | null; voice_duration_seconds: number | null; category: string; status: string | null; created_at: string; profiles: Profile | null };

function Avatar({ profile }: { profile: Profile | null }) { return <div className="avatar">{profile?.avatar_url ? <img src={profile.avatar_url} alt="" className="avatar-image" /> : profile?.display_name?.[0]?.toUpperCase() ?? "G"}</div>; }

export default function PostPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const supabase = useMemo(() => createClient(), []);
  const [post, setPost] = useState<Post | null>(null); const [editing, setEditing] = useState(false); const [editText, setEditText] = useState(""); const [editCategory, setEditCategory] = useState(""); const [editPhoto, setEditPhoto] = useState<File | null>(null); const [editPhotoPreview, setEditPhotoPreview] = useState(""); const [editBusy, setEditBusy] = useState(false); const [commentsOnly, setCommentsOnly] = useState(false); const [menuOpen, setMenuOpen] = useState(false); const [menuBusy, setMenuBusy] = useState(false); const [comments, setComments] = useState<Comment[]>([]); const [userId, setUserId] = useState<string | null>(null); const [text, setText] = useState(""); const [voice, setVoice] = useState<Blob | null>(null); const [recording, setRecording] = useState(false); const [seconds, setSeconds] = useState(0); const [replyText, setReplyText] = useState<Record<string, string>>({}); const [replyVoice, setReplyVoice] = useState<Record<string, Blob | null>>({}); const [replyRecording, setReplyRecording] = useState<string | null>(null); const [replySeconds, setReplySeconds] = useState<Record<string, number>>({}); const [likeCount, setLikeCount] = useState(0); const [liked, setLiked] = useState(false); const [saved, setSaved] = useState(false); const [showDetails, setShowDetails] = useState(false); const [openReply, setOpenReply] = useState<string | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const [renderedAt, setRenderedAt] = useState<number | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => setRenderedAt(Date.now()), 0); return () => window.clearTimeout(timer); }, []);

  const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]); const timer = useRef<ReturnType<typeof setInterval> | null>(null); const replyRecorder = useRef<MediaRecorder | null>(null); const replyChunks = useRef<Blob[]>([]); const replyTimer = useRef<ReturnType<typeof setInterval> | null>(null);

  const load = useCallback(async (currentUserId: string | null) => {
    setError("");
    const [postResult, commentsResult, likeResult, savedResult] = await Promise.all([
      supabase.from("posts").select("id,author_id,body,content_type,media_url,voice_duration_seconds,category,status,created_at").eq("id", id).single(),
      supabase.from("responses").select("id,body,content_type,media_url,voice_duration_seconds,created_at,author_id,replies(id,body,content_type,media_url,voice_duration_seconds,created_at,author_id)").eq("post_id", id).order("created_at", { ascending: true }),
      supabase.from("likes").select("post_id,user_id", { count: "exact" }).eq("post_id", id),
      currentUserId ? supabase.from("saves").select("post_id").eq("post_id", id).eq("user_id", currentUserId).maybeSingle() : Promise.resolve({ data: null, error: null }),
    ]);
    if (postResult.error) { setError(postResult.error.message); setLoading(false); return; }
    const rawPost = postResult.data as Omit<Post, "profiles">;
    const rawComments = (commentsResult.data ?? []) as Array<Omit<Comment, "profiles" | "replies" | "likes" | "liked"> & { replies: Array<Omit<Reply, "profiles" | "likes" | "liked">> }>;
    if (commentsResult.error) setError(commentsResult.error.message);
    const commentIds = rawComments.map((item) => item.id); const replyIds = rawComments.flatMap((item) => (item.replies ?? []).map((reply) => reply.id));
    const authorIds = [rawPost.author_id, ...rawComments.map((item) => item.author_id), ...rawComments.flatMap((item) => (item.replies ?? []).map((reply) => reply.author_id))]; const uniqueAuthorIds = [...new Set(authorIds)];
    const [profilesResult, commentLikesResult, replyLikesResult, myLikeResult] = await Promise.all([
      supabase.from("profiles").select("id,display_name,username,avatar_url").in("id", uniqueAuthorIds),
      commentIds.length ? supabase.from("response_likes").select("response_id,user_id").in("response_id", commentIds) : Promise.resolve({ data: [] as { response_id: string; user_id: string }[] }),
      replyIds.length ? supabase.from("reply_likes").select("reply_id,user_id").in("reply_id", replyIds) : Promise.resolve({ data: [] as { reply_id: string; user_id: string }[] }),
      currentUserId ? supabase.from("likes").select("post_id").eq("post_id", id).eq("user_id", currentUserId).maybeSingle() : Promise.resolve({ data: null, error: null }),
    ]);
    const profiles = new Map((profilesResult.data ?? []).map((profile) => [profile.id, profile as Profile])); const commentLikes: Record<string, number> = {}; const replyLikes: Record<string, number> = {}; const likedComments = new Set<string>(); const likedReplies = new Set<string>();
    (commentLikesResult.data ?? []).forEach((item) => { commentLikes[item.response_id] = (commentLikes[item.response_id] ?? 0) + 1; if (item.user_id === currentUserId) likedComments.add(item.response_id); });
    (replyLikesResult.data ?? []).forEach((item) => { replyLikes[item.reply_id] = (replyLikes[item.reply_id] ?? 0) + 1; if (item.user_id === currentUserId) likedReplies.add(item.reply_id); });
    setPost({ ...rawPost, profiles: profiles.get(rawPost.author_id) ?? null }); setLikeCount(likeResult.count ?? 0); setLiked(Boolean(myLikeResult.data)); setSaved(Boolean(savedResult.data));
    setComments(rawComments.map((item) => ({ ...item, profiles: profiles.get(item.author_id) ?? null, likes: commentLikes[item.id] ?? 0, liked: likedComments.has(item.id), replies: (item.replies ?? []).map((reply) => ({ ...reply, profiles: profiles.get(reply.author_id) ?? null, likes: replyLikes[reply.id] ?? 0, liked: likedReplies.has(reply.id) })) })));
    setLoading(false);
  }, [id, supabase]);

  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.get("dna") === "1") setShowDetails(true); setCommentsOnly(params.get("comments") === "1"); }, []);

  useEffect(() => { let active = true; void supabase.auth.getSession().then(({ data }) => { if (!active) return; const uid = data.session?.user?.id ?? null; setUserId(uid); void load(uid); }); return () => { active = false; }; }, [load, supabase]);
  function authRequired() { if (userId) return true; router.push(`/auth?returnTo=${encodeURIComponent(`/post/${id}`)}`); return false; }
  function startEditPost() { if (!post || userId !== post.author_id || menuBusy || editBusy) return; setMenuOpen(false); setEditText(post.body ?? ""); setEditCategory(post.category); setEditPhoto(null); setEditPhotoPreview(post.content_type === "photo" ? (post.media_url ?? "") : ""); setEditing(true); }
  function cancelEditPost() { if (editPhotoPreview && editPhotoPreview !== post?.media_url) URL.revokeObjectURL(editPhotoPreview); setEditPhoto(null); setEditPhotoPreview(""); setEditing(false); }
  function handleEditPhoto(file: File | null) { if (!file) return; if (!["image/jpeg","image/png","image/webp"].includes(file.type)) { setError("Use a JPG, PNG, or WebP image."); return; } if (file.size > 10 * 1024 * 1024) { setError("Post photos must be 10MB or smaller."); return; } if (editPhotoPreview && editPhotoPreview !== post?.media_url) URL.revokeObjectURL(editPhotoPreview); setEditPhoto(file); setEditPhotoPreview(URL.createObjectURL(file)); setError(""); }
  async function saveEditPost() { if (!userId || !post || userId !== post.author_id || editBusy) return; if (!editCategory) { setError("Choose a category."); return; } if (post.content_type === "text" && !editText.trim()) { setError("Write something before saving."); return; } setEditBusy(true); setError(""); let mediaUrl = post.media_url; if (post.content_type === "photo" && editPhoto) { const path = `${userId}/${crypto.randomUUID()}.jpg`; const upload = await supabase.storage.from("gist-media").upload(path, editPhoto, { contentType: "image/jpeg", cacheControl: "31536000", upsert: false }); if (upload.error) { setError(upload.error.message); setEditBusy(false); return; } mediaUrl = supabase.storage.from("gist-media").getPublicUrl(path).data.publicUrl; } const result = await supabase.from("posts").update({ body: editText.trim() || null, category: editCategory, media_url: mediaUrl }).eq("id", id).eq("author_id", userId); if (result.error) { setError(result.error.message); setEditBusy(false); return; } setPost((current) => current ? { ...current, body: editText.trim() || null, category: editCategory, media_url: mediaUrl } : current); setEditBusy(false); cancelEditPost(); }
  async function deletePost() { if (!userId || !post || userId !== post.author_id || menuBusy) return; setMenuBusy(true); setMenuOpen(false); setError(""); const result = await supabase.from("posts").delete().eq("id", id).eq("author_id", userId).select("id").maybeSingle(); if (result.error) { setError(result.error.message); setMenuBusy(false); return; } if (!result.data) { setError("The Post could not be deleted. Please refresh and try again."); setMenuBusy(false); return; } router.replace("/profile"); router.refresh(); }
  async function hidePost() { if (!userId || !post || userId !== post.author_id || menuBusy) return; setMenuBusy(true); const result = await supabase.from("not_interested").upsert({ user_id: userId, post_id: id }, { onConflict: "user_id,post_id" }); if (result.error) { setError(result.error.message); setMenuBusy(false); return; } router.back(); }
  async function togglePostLike() { if (!authRequired()) return; const next = !liked; setLiked(next); setLikeCount((count) => Math.max(0, count + (next ? 1 : -1))); const result = next ? await supabase.from("likes").insert({ post_id: id, user_id: userId }) : await supabase.from("likes").delete().eq("post_id", id).eq("user_id", userId); if (result.error) { setLiked(!next); setLikeCount((count) => Math.max(0, count + (next ? -1 : 1))); setError(result.error.message); } }
  async function toggleSave() { if (!authRequired()) return; const next = !saved; setSaved(next); const result = next ? await supabase.from("saves").insert({ post_id: id, user_id: userId }) : await supabase.from("saves").delete().eq("post_id", id).eq("user_id", userId); if (result.error) { setSaved(!next); setError(result.error.message); } }
  async function sharePost() { if (!authRequired()) return; const url = `${window.location.origin}/post/${id}`; try { if (navigator.share) await navigator.share({ title: "Gista", text: post?.body ?? "Check out this Post on Gista", url }); else await navigator.clipboard.writeText(url); await supabase.from("shares").insert({ post_id: id, user_id: userId }); } catch {} }
  function stopRecording() { if (recorder.current?.state === "recording") recorder.current.stop(); if (timer.current) clearInterval(timer.current); timer.current = null; setRecording(false); }
  async function startRecording() { if (!authRequired()) return; try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); chunks.current = []; const mediaRecorder = new MediaRecorder(stream); recorder.current = mediaRecorder; let elapsed = 0; setSeconds(0); mediaRecorder.ondataavailable = (event) => { if (event.data.size) chunks.current.push(event.data); }; mediaRecorder.onstop = () => { stream.getTracks().forEach((track) => track.stop()); setVoice(new Blob(chunks.current, { type: mediaRecorder.mimeType || "audio/webm" })); }; mediaRecorder.start(); setRecording(true); timer.current = setInterval(() => { elapsed += 1; setSeconds(elapsed); if (elapsed >= 60) stopRecording(); }, 1000); } catch { setError("Microphone access is required for a voice comment."); } }
  async function postComment() { if (!authRequired() || (!text.trim() && !voice)) return; setError(""); let mediaUrl: string | null = null; if (voice) { const path = `${userId}/${crypto.randomUUID()}.webm`; const upload = await supabase.storage.from("gist-audio").upload(path, voice, { contentType: voice.type || "audio/webm" }); if (upload.error) { setError(upload.error.message); return; } mediaUrl = supabase.storage.from("gist-audio").getPublicUrl(path).data.publicUrl; } const result = await supabase.from("responses").insert({ post_id: id, author_id: userId, content_type: voice ? "voice" : "text", body: voice ? null : text.trim(), media_url: mediaUrl, voice_duration_seconds: voice ? seconds : null }); if (result.error) { setError(result.error.message); return; } setText(""); setVoice(null); setSeconds(0); void load(userId); }
  async function toggleCommentLike(comment: Comment) { if (!authRequired()) return; const next = !comment.liked; const result = next ? await supabase.from("response_likes").insert({ response_id: comment.id, user_id: userId }) : await supabase.from("response_likes").delete().eq("response_id", comment.id).eq("user_id", userId); if (!result.error) setComments((items) => items.map((item) => item.id === comment.id ? { ...item, liked: next, likes: Math.max(0, item.likes + (next ? 1 : -1)) } : item)); else setError(result.error.message); }
  async function toggleReplyLike(commentId: string, reply: Reply) { if (!authRequired()) return; const next = !reply.liked; const result = next ? await supabase.from("reply_likes").insert({ reply_id: reply.id, user_id: userId }) : await supabase.from("reply_likes").delete().eq("reply_id", reply.id).eq("user_id", userId); if (!result.error) setComments((items) => items.map((item) => item.id === commentId ? { ...item, replies: item.replies.map((entry) => entry.id === reply.id ? { ...entry, liked: next, likes: Math.max(0, entry.likes + (next ? 1 : -1)) } : entry) } : item)); else setError(result.error.message); }
  function stopReplyRecording() { if (replyRecorder.current?.state === "recording") replyRecorder.current.stop(); if (replyTimer.current) clearInterval(replyTimer.current); replyTimer.current = null; setReplyRecording(null); }
  async function startReplyRecording(commentId: string) { if (!authRequired()) return; try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); replyChunks.current = []; const mediaRecorder = new MediaRecorder(stream); replyRecorder.current = mediaRecorder; let elapsed = 0; setReplySeconds((current) => ({ ...current, [commentId]: 0 })); mediaRecorder.ondataavailable = (event) => { if (event.data.size) replyChunks.current.push(event.data); }; mediaRecorder.onstop = () => { stream.getTracks().forEach((track) => track.stop()); setReplyVoice((current) => ({ ...current, [commentId]: new Blob(replyChunks.current, { type: mediaRecorder.mimeType || "audio/webm" }) })); }; mediaRecorder.start(); setReplyRecording(commentId); replyTimer.current = setInterval(() => { elapsed += 1; setReplySeconds((current) => ({ ...current, [commentId]: elapsed })); if (elapsed >= 60) stopReplyRecording(); }, 1000); } catch { setError("Microphone access is required for a voice reply."); } }
  async function postReply(comment: Comment) { if (!authRequired()) return; const body = (replyText[comment.id] ?? "").trim(); const voiceReply = replyVoice[comment.id] ?? null; if (!body && !voiceReply) return; let mediaUrl: string | null = null; if (voiceReply) { const path = `${userId}/${crypto.randomUUID()}.webm`; const upload = await supabase.storage.from("gist-audio").upload(path, voiceReply, { contentType: voiceReply.type || "audio/webm" }); if (upload.error) { setError(upload.error.message); return; } mediaUrl = supabase.storage.from("gist-audio").getPublicUrl(path).data.publicUrl; } const result = await supabase.from("replies").insert({ response_id: comment.id, author_id: userId, content_type: voiceReply ? "voice" : "text", body: voiceReply ? null : body, media_url: mediaUrl, voice_duration_seconds: voiceReply ? (replySeconds[comment.id] ?? 0) : null }); if (result.error) { setError(result.error.message); return; } setReplyText((current) => ({ ...current, [comment.id]: "" })); setReplyVoice((current) => ({ ...current, [comment.id]: null })); setReplySeconds((current) => ({ ...current, [comment.id]: 0 })); setOpenReply(null); void load(userId); }

  if (loading) return <main className="content"><div className="feed-skeleton"><div className="skeleton-post"/><div className="skeleton-post"/></div></main>;
  if (!post) return <main className="content"><Link href="/">← Back Home</Link><div className="empty-state"><h3>Post not found</h3><p>{error || "This Post may have been removed."}</p></div></main>;

  const voiceComments = comments.filter((item) => item.content_type === "voice").length; const textComments = comments.length - voiceComments; const participants = new Set([post.author_id, ...comments.map((item) => item.author_id), ...comments.flatMap((item) => item.replies.map((reply) => reply.author_id))]).size; const ageHours = Math.max(1, ((renderedAt ?? Date.parse(post.created_at)) - Date.parse(post.created_at)) / 3600000); const commentGrowth = (comments.length / ageHours).toFixed(1); const voiceMix = Math.round((voiceComments / Math.max(1, comments.length)) * 100); const textMix = 100 - voiceMix;
  const statusLabel = post.status ? post.status.charAt(0).toUpperCase() + post.status.slice(1) : "Growing";
  const isOwner = userId === post.author_id;
  const showComments = commentsOnly || !isOwner;

  return <main className="app-shell">
    <header className="simple-header"><button className="back-link" onClick={() => router.back()}><ArrowLeft size={18}/><span>Back</span></button><strong>Post</strong>{isOwner ? <div className="post-owner-menu"><button className="icon-btn" type="button" aria-label="Post options" aria-expanded={menuOpen} onClick={() => setMenuOpen((value) => !value)}><MoreHorizontal size={20}/></button>{menuOpen && <div className="post-menu" role="menu"><button type="button" onClick={startEditPost} disabled={menuBusy || editBusy}>Edit Post</button><button type="button" onClick={() => void hidePost()} disabled={menuBusy || editBusy}>Hide Post</button><button type="button" className="danger" onClick={() => void deletePost()} disabled={menuBusy || editBusy}>Delete Post</button></div>}</div> : <span className="header-spacer" aria-hidden="true" />}</header>
    <section className="content post-detail-content">
      {editing && isOwner ? <section className="post-edit-card"><div className="post-edit-header"><strong>Edit Post</strong><button type="button" onClick={cancelEditPost} disabled={editBusy}>Cancel</button></div><textarea value={editText} onChange={(event) => setEditText(event.target.value)} maxLength={5000} placeholder="Say something worth sharing…"/>{post.content_type === "photo" && <div className="post-edit-photo"><label htmlFor="edit-post-photo"><ImagePlus size={18}/><span>Change photo</span></label><input id="edit-post-photo" type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={(event) => { handleEditPhoto(event.target.files?.[0] ?? null); event.currentTarget.value = ""; }}/>{editPhotoPreview && <img src={editPhotoPreview} alt="Post preview"/>}</div>}<select value={editCategory} onChange={(event) => setEditCategory(event.target.value)}><option value="" disabled>Choose a category</option>{["Music","Movies / Entertainment","Art","Banter","Fun","Gossip","Sports","Relationships","Business","Technology","Education","Lifestyle","Society","News & Current Events","Opinions","Stories"].map((item) => <option key={item} value={item}>{item}</option>)}</select>{error && <div className="auth-message">{error}</div>}<button type="button" className="primary" onClick={() => void saveEditPost()} disabled={editBusy}>{editBusy ? "Saving…" : "Save Changes"}</button></section> : null}
      
      {!commentsOnly && <article className="post post-detail">
        <div className="post-head"><Link href={post.profiles?.username ? `/profile/${post.profiles.username}` : "/profile"}><Avatar profile={post.profiles}/></Link><div className="identity"><Link href={post.profiles?.username ? `/profile/${post.profiles.username}` : "/profile"}><strong>{post.profiles?.display_name ?? "Gista User"}</strong></Link><span>@{post.profiles?.username ?? "user"} · {new Date(post.created_at).toLocaleString()}</span></div><span className="category">{post.category}</span></div>
        {post.body && <p className="post-text">{post.body}</p>}
        {post.content_type === "photo" && post.media_url && <div className="post-media"><img src={post.media_url} alt="Post" className="gist-media"/></div>}
        {post.content_type === "voice" && post.media_url && <VoiceNote src={post.media_url} durationHint={post.voice_duration_seconds ?? 0}/>}
        <div className="post-meta"><button className="post-dna" type="button" onClick={() => setShowDetails((value) => !value)}>Post DNA</button><span className="gist-status"><span className="dot">●</span>{statusLabel}</span></div>
        {showDetails && <div className="post-dna-panel"><strong>Post DNA</strong><div><span>Status</span><b className="dna-status">{statusLabel}</b></div><div><span>Participants</span><b>{participants}</b></div><div><span>Comments</span><b>{comments.length}</b></div><div><span>Comment growth</span><b>{commentGrowth}/hr</b></div><div><span>Voice comments</span><b>{voiceComments}</b></div><div><span>Text comments</span><b>{textComments}</b></div><div><span>Voice mix</span><b>{voiceMix}%</b></div><div><span>Text mix</span><b>{textMix}%</b></div><div><span>Likes</span><b>{likeCount}</b></div><div><span>Format</span><b>{post.content_type}</b></div><div><span>Category</span><b>{post.category}</b></div></div>}
        <div className="post-actions"><button type="button" className={liked ? "post-like-action liked" : "post-like-action"} onClick={() => void togglePostLike()}><Heart size={18} fill={liked ? "currentColor" : "none"}/><span>{likeCount}</span></button><button type="button" onClick={() => { setCommentsOnly(true); window.history.replaceState(null, "", `/post/${id}?comments=1`); setTimeout(() => document.getElementById("comment-box")?.focus(), 0); }}><span>💬</span><span>{comments.length}</span></button><button type="button" onClick={() => void sharePost()}><Share2 size={18}/></button><button type="button" className={saved ? "post-save-action saved" : "post-save-action"} onClick={() => void toggleSave()}><Bookmark size={18} fill={saved ? "currentColor" : "none"}/></button></div>
      </article>}
      {showComments && <section className={`comments-section${commentsOnly ? " comments-only" : ""}`}>
        <h2>Comments</h2>
        <div className="comment-composer"><textarea id="comment-box" value={text} onChange={(event) => setText(event.target.value)} placeholder="Write a comment…" rows={4}/><div className="comment-composer-actions"><button type="button" className={recording ? "voice-record recording" : "voice-record"} onClick={() => recording ? stopRecording() : void startRecording()}>{recording ? <><Square size={16} fill="currentColor"/> Stop {seconds}s</> : <><Mic size={17}/> Voice comment</>}</button><button type="button" className="primary" onClick={() => void postComment()} disabled={!text.trim() && !voice}>Post comment</button></div>{voice&&<small>Voice comment ready ({seconds}s)</small>}</div>
        {error&&<p className="auth-message">{error}</p>}
        <div className="comments-list">{comments.length===0?<p className="profile-empty">No comments yet. Be the first to comment.</p>:comments.map((comment)=><article className="comment" key={comment.id}>
          <div className="comment-head"><Avatar profile={comment.profiles}/><div><strong>{comment.profiles?.display_name??"Gista User"}</strong><span>@{comment.profiles?.username??"user"} · {new Date(comment.created_at).toLocaleString()}</span></div></div>
          {comment.body&&<p>{comment.body}</p>}{comment.content_type==="voice"&&comment.media_url&&<VoiceNote src={comment.media_url} durationHint={comment.voice_duration_seconds??0}/>}<div className="comment-actions"><button type="button" className={comment.liked?"response-like liked":"response-like"} onClick={()=>void toggleCommentLike(comment)}><Heart size={16} fill={comment.liked?"currentColor":"none"}/> <span className="like-count">{comment.likes}</span></button><button type="button" onClick={()=>setOpenReply((current)=>current===comment.id?null:comment.id)}>Reply {comment.replies.length?`(${comment.replies.length})`:""}</button></div>
          {comment.replies.length>0&&<div className="replies-list">{comment.replies.map((reply)=><div className="reply" key={reply.id}><div className="comment-head"><Avatar profile={reply.profiles}/><div><strong>{reply.profiles?.display_name??"Gista User"}</strong><span>@{reply.profiles?.username??"user"} · {new Date(reply.created_at).toLocaleString()}</span></div></div>{reply.body&&<p>{reply.body}</p>}{reply.content_type==="voice"&&reply.media_url&&<VoiceNote src={reply.media_url} durationHint={reply.voice_duration_seconds??0}/>}<div className="comment-actions"><button type="button" className={reply.liked?"reply-like liked":"reply-like"} onClick={()=>void toggleReplyLike(comment.id,reply)}><Heart size={15} fill={reply.liked?"currentColor":"none"}/> <span className="like-count">{reply.likes}</span></button></div></div>)}</div>}
          {openReply===comment.id&&<div className="reply-composer"><textarea value={replyText[comment.id]??""} onChange={(event)=>setReplyText((current)=>({...current,[comment.id]:event.target.value}))} placeholder="Write a reply…" rows={2}/><div className="comment-composer-actions"><button type="button" className={replyRecording===comment.id?"voice-record recording":"voice-record"} onClick={()=>replyRecording===comment.id?stopReplyRecording():void startReplyRecording(comment.id)}>{replyRecording===comment.id?<><Square size={15} fill="currentColor"/> Stop {replySeconds[comment.id]??0}s</>:<><Mic size={16}/> Voice reply</>}</button><button type="button" className="primary" onClick={()=>void postReply(comment)} disabled={!((replyText[comment.id]??"").trim())&&!replyVoice[comment.id]}>Post reply</button></div></div>}
        </article>)}</div>
      </section>}
    </section>
  </main>;
}
